name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push:
    name: Push Docker image to Docker Hub
    
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: yjl9903
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: yjl9903/sandbox
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=ref,event=branch,enable=true,priority=600
            type=semver,event=tag,pattern={{version}},enable=true,priority=600
            type=schedule,pattern=nightly,enable=true,priority=1000

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./sandbox
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
